[package]
name = "superposition-assets"
version = "0.4.0"
edition = "2024"
license = "MIT"
description = "Superposition Assets supported on Arbitrum One."
homepage = "https://fluiditylabs.io"
repository = "https://github.com/fluidity-money/superposition-assets"

[dependencies]
arbitrary = { version = ">=1.4.0", features = ["derive"], optional = true }
borsh = { version = ">=1.8.0", default-features = false, features = ["derive"], optional = true }
const-hex = { version = "1.19.1", default-features = false }
proptest = { version = ">=1.0.0", optional = true }
proptest-derive = { version = ">=0.8.0", optional = true }
serde = { version = ">=1.0.0", default-features = false, features = ["alloc", "derive"], optional = true }

[features]
default = ["alloc"]
borsh = ["dep:borsh"]
proptest = ["dep:proptest", "dep:proptest-derive"]
arbitrary = ["dep:arbitrary"]
serde = ["dep:serde"]
alloc = []
